USE EMPLOYEETRACKER_DB;

USE EMPLOYEETRACKER_DB;

INSERT INTO DEPARTMENT (NAME) VALUES ('FRONTEND');
INSERT INTO DEPARTMENT (NAME) VALUES ('BACKEND');

USE EMPLOYEETRACKER_DB;
INSERT INTO ROLE (TITLE,SALARY,DEPARTMENT_ID) VALUES ('FRONT END MANAGER',80000,1);
INSERT INTO ROLE (TITLE,SALARY,DEPARTMENT_ID) VALUES ('USER INTERFACE',70000,1);
INSERT INTO ROLE (TITLE,SALARY,DEPARTMENT_ID) VALUES ('JAVASCRIPT FRONT END',70000,1);
INSERT INTO ROLE (TITLE,SALARY,DEPARTMENT_ID) VALUES ('BACK END MANAGER',80000,2);
INSERT INTO ROLE (TITLE,SALARY,DEPARTMENT_ID) VALUES ('DATABASE',70000,2);
INSERT INTO ROLE (TITLE,SALARY,DEPARTMENT_ID) VALUES ('JAVASCRIPT BACK END',70000,2);

USE EMPLOYEETRACKER_DB;
INSERT INTO EMPLOYEE (FIRST_NAME,LAST_nAME,ROLE_ID,MANAGER_ID) VALUES ("BLACK","PANTHER",6,2);

//select all
select E1.first_name, E1.last_name, role.title, role.salary, department.name, E2.first_name as manager
from employee E1
left join role on E1.role_id = role.id 
left join department on role.department_id = department.id
left JOIN employee E2 on E2.id = e1.manager_id









INSERT INTO DEPARTMENT (NAME) VALUES ('ACCOUNTING');
INSERT INTO DEPARTMENT (NAME) VALUES ('HR');
INSERT INTO DEPARTMENT (NAME) VALUES ('SALES');
INSERT INTO DEPARTMENT (NAME) VALUES ('MARKETING');
INSERT INTO DEPARTMENT (NAME) VALUES ('IT');

INSERT INTO ROLE (TITLE,SALARY,DEPARTMENT_ID) VALUES ('PAYABLE',50000,1);
INSERT INTO ROLE (TITLE,SALARY,DEPARTMENT_ID) VALUES ('RECEIVABLE',50000,1);

INSERT INTO ROLE (TITLE,SALARY,DEPARTMENT_ID) VALUES ('PAYROLL',60000,2);
INSERT INTO ROLE (TITLE,SALARY,DEPARTMENT_ID) VALUES ('RECRUITMENT',40000,2);

INSERT INTO ROLE (TITLE,SALARY,DEPARTMENT_ID) VALUES ("MANAGER", 80000,3);
INSERT INTO ROLE (TITLE,SALARY,DEPARTMENT_ID) VALUES ("ASSISTANT MANAGER", 60000,3);

INSERT INTO ROLE (TITLE,SALARY,DEPARTMENT_ID) VALUES ("MARKETING HEAD",50000,4);
INSERT INTO ROLE (TITLE,SALARY,DEPARTMENT_ID) VALUES ("SOCIAL MEDIA", 40000,4);

INSERT INTO ROLE (TITLE,SALARY,DEPARTMENT_ID) VALUES ("PROJECT MANAGER",90000,5);
INSERT INTO ROLE (TITLE,SALARY,DEPARTMENT_ID) VALUES ("FRONTEND", 60000,5);
INSERT INTO ROLE (TITLE,SALARY,DEPARTMENT_ID) VALUES ("BACKEND", 60000,5);